version: '3.8'

services:
  database:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "MyPass@word"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
      MSSQL_DATABASE: "product_service"
    ports:
      - "1433:1433"
    container_name: product_service